language: java
jdk:
  - oraclejdk8

before_install:
 - chmod +x gradlew

install:
  - gradle assemble

script:
  - gradle check

#after_success:
# - ./gradlew jacocoTestReport
# - pip install --user codecov
# - codecov 
  
 
